language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 7 

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.3.3
    - php: 7 

before_install:

install:
      - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
 - ant travis -keep-going

notifications:
  email:
      - swansoft_team@groups.163.com
